[versions]
compileSdk = "36"
minSdk = "28"

android-plugin = "8.13.1"
kotlin = "2.2.21"

activity = "1.12.0"

compose = "1.9.5"

core = "1.17.0"
core-splashscreen = "1.2.0"

appcompat = "1.7.1"

compose-bom = "2025.11.01"
lifecycle = "2.10.0"
material = "1.4.0"
material-icons = '1.7.8'

media3 = "1.8.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material-icons" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }

lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-media3 = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3" }

[plugins]
android = { id = "com.android.application", version.ref = "android-plugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
